apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: descomplicando-gitops-argocd/app-of-apps
#    helm:
#      parameters:
#        - name: "argocd.giropopsSenhas.enabled"
#          value: "false"
#        - name: "argocd.randomLogger.enabled"
#          value: "false"  
    repoURL: https://github.com/maycon1986/LINUXTIPS-PICK2024.git
    targetRevision: feat/day2 # Branch
  syncPolicy:
    automated:
      selfHeal: true # True ele sempre vai respeitar o que esta no repositorio, mesmo alterando diretamente no cluster.
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true # Para realizar o delete.