apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    targetRevision: 11.2.1
    helm:
      valueFiles:
      - $values/descomplicando-gitops-argocd/grafana/values.yaml
  - repoURL: 'https://github.com/maycon1986/LINUXTIPS-PICK2024.git'
    targetRevision: feat/day2
    ref: values
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
      PruneLast=true
      