apiVersion: v1
kind: Service
metadata:
  name: nginx1 # Colocar o mesmo nome do "serviceName" do statefulset
  labels:
    app: nginx-svc1
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None # Como estamos criando um Headless Service, não queremos que ele tenha um IP, então definimos o clusterIP como None
  selector:
    app: nginx2