{{ if .Values.argocd.giropopsSenhas.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: giropops-senhas
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: "giropopsSenhas.replicas"
        value: {{ .Values.argocd.giropopsSenhas.replicas }}    
    path: descomplicando-gitops-argocd/giropops-senhas/helm
    repoURL: https://github.com/maycon1986/LINUXTIPS-PICK2024.git
    targetRevision: feat/day2
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
      PruneLast=true
{{ end }}