{{ if .Values.argocd.randomLogger.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-logger
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: random-logger
    server: https://kubernetes.default.svc
  project: default
  source:
    path: descomplicando-gitops-argocd/random-logger/helm
    repoURL: https://github.com/maycon1986/LINUXTIPS-PICK2024.git
    targetRevision: feat/day2
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
      PruneLast=true
{{ end }}