apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-configmap-for-namespace
spec:
  rules:
  - name: generate-namespace-configmap
    match:
      resources:
        kinds:
        - Namespace
    generate:
      apiVersion: v1
      kind: ConfigMap
      name: default-configmap
      namespace: "{{request.object.metadata.name}}"
      data:
        data:
          key1: "value1"
          key2: "value2"