apiVersion: v1
kind: Pod
metadata:
  labels:
    run: deltcom-web
  name: deltcom-web
spec:
  containers:
  - image: nginx
    name: deltcom-web
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}