apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-svc
spec:
  ports:
  - port: 9113 # porta do svc
    name: metrics # nome da porta
  selector:
    app: nginx-deployment