apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  selector:
    matchLabels: 
      app: nginx-deployment
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx-deployment
      annotations:
        prometheus.io/scrape: 'true' # habilita o scraping do Prometheus
        prometheus.io/port: '9113' # porta do target
    spec: 
      containers: 
        - name: nginx 
          image: nginx
          ports: 
            - containerPort: 80
              name: http 
          volumeMounts: 
            - name: nginx-config 
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf 
        - name: nginx-exporter # nome do container que será o exporter
          image: 'nginx/nginx-prometheus-exporter:0.11.0'
          args: # argumentos do container
            - '-nginx.scrape-uri=http://localhost/metrics' # argumento para definir a URI de scraping
          resources: 
            limits: 
              memory: 128Mi
              cpu: 0.5
          ports: 
            - containerPort: 9113
              name: metrics 
      volumes: 
        - configMap: 
            defaultMode: 420 # modo padrão do volume
            name: nginx-config 
          name: nginx-config 