apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-prometheus-prometheus-rule
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
spec:
  groups:
  - name: nginx-prometheus-rule
    rules:
    - alert: NginxDown
      expr: nginx_up == 0
      for: 1m # Tem que ficar 0 no minito 1m
      labels:
        severity: critical
      annotations:
        summary: "Nginx está fora"
        description: "O nosso servidor web nginx está fora! {{ $labels.pod }}"
    
    - alert: NginxHighRequestsRate
      expr: rate(nginx_http_requests_total[5m]) > 10
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "O Nginx está recebendo um número alto de request"
        description: "O Nginx está com um numero alto de requisições."