apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: lento
  name: meu-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # Pode ler e escrever, somente por um unico nó
  persistentVolumeReclaimPolicy: Retain # Ele vai reter o PV quando o pvc for excluido.
  hostPath: # Pode ser utilizado outras opções como NFS.
    path: /mnt/data
  storageClassName: giropos