apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "deployments"]
  verbs: ["list", "create", "get", "delete"]